services:
  dedalus-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DATABASE=
      - JWT_REFRESH_SECRET=
      - WEB_APP_URL=
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - dedalus-db
  dedalus-db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_TCP_PORT=